# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

services:
  embedding-mosec:
    build:
      dockerfile: comps/3rd_parties/mosec/deployment/docker/Dockerfile
    image: ${REGISTRY:-opea}/embedding-mosec:${TAG:-latest}
  nginx:
    build:
      dockerfile: comps/3rd_parties/nginx/src/Dockerfile
    image: ${REGISTRY:-opea}/nginx:${TAG:-latest}
