# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

include:
  - ../../../third_parties/redis/deployment/docker_compose/compose.yaml
  - ../../../third_parties/tei/deployment/docker_compose/compose.yaml

services:
  retriever:
    image: ${REGISTRY:-opea}/retriever:${TAG:-latest}
    container_name: retriever
    ports:
      - "${RETRIEVER_PORT:-7000}:7000"
    ipc: host
    environment:
      no_proxy: ${no_proxy}
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
      REDIS_URL: ${REDIS_URL}
      INDEX_NAME: ${INDEX_NAME}
      TEI_EMBEDDING_ENDPOINT: ${TEI_EMBEDDING_ENDPOINT}
      HUGGINGFACEHUB_API_TOKEN: ${HF_TOKEN}
      BRIDGE_TOWER_EMBEDDING: ${BRIDGE_TOWER_EMBEDDING}
      LOGFLAG: ${LOGFLAG:-False}
    restart: unless-stopped

  retriever-redis:
    extends: retriever
    container_name: retriever-redis
    environment:
      RETRIEVER_COMPONENT_NAME: ${RETRIEVER_COMPONENT_NAME:-OPEA_RETRIEVER_REDIS}
    depends_on:
      redis-vector-db:
        condition: service_healthy
      tei-embedding-serving:
        condition: service_healthy

  retriever-redis-multimodal:
    extends: retriever
    container_name: retriever-redis-multimodal
    environment:
      RETRIEVER_COMPONENT_NAME: ${RETRIEVER_COMPONENT_NAME:-OPEA_RETRIEVER_REDIS}
      RETRIEVER_TYPE: ${RETRIEVER_TYPE:-redis}
    depends_on:
      redis-vector-db:
        condition: service_healthy


networks:
  default:
    driver: bridge
