# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

include:
  - ../../../third_parties/tgi/deployment/docker_compose/compose.yaml
  - ../../../third_parties/vllm/deployment/docker_compose/compose.yaml

services:
  textgen:
    image: ${REGISTRY:-opea}/llm-textgen:${TAG:-latest}
    container_name: llm-textgen-server
    ports:
      - ${TEXTGEN_PORT:-9000}:9000
    ipc: host
    environment:
      no_proxy: ${no_proxy}
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
      LLM_ENDPOINT: ${LLM_ENDPOINT}
      LLM_MODEL_ID: ${LLM_MODEL_ID}
      HF_TOKEN: ${HF_TOKEN}
      LOGFLAG: ${LOGFLAG:-False}
    restart: unless-stopped

  textgen-service-tgi:
    extends: textgen
    container_name: textgen-service-tgi
    environment:
      LLM_COMPONENT_NAME: ${LLM_COMPONENT_NAME:-OpeaTextGenService}
    depends_on:
      tgi-server:
        condition: service_healthy

  textgen-service-tgi-gaudi:
    extends: textgen
    container_name: textgen-service-tgi-gaudi
    environment:
      LLM_COMPONENT_NAME: ${LLM_COMPONENT_NAME:-OpeaTextGenService}
    depends_on:
      tgi-gaudi-server:
        condition: service_healthy

  textgen-service-vllm:
    extends: textgen
    container_name: textgen-service-vllm
    environment:
      LLM_COMPONENT_NAME: ${LLM_COMPONENT_NAME:-OpeaTextGenService}
    depends_on:
      vllm-server:
        condition: service_healthy

  textgen-service-vllm-gaudi:
    extends: textgen
    container_name: textgen-service-vllm-gaudi
    environment:
      LLM_COMPONENT_NAME: ${LLM_COMPONENT_NAME:-OpeaTextGenService}
    depends_on:
      vllm-gaudi-server:
        condition: service_healthy

networks:
  default:
    driver: bridge
